import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./providers/AuthContext";
import AccessProvider from "./providers/AccessProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <AccessProvider>{children}</AccessProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
